# Generated by Django 3.1.1 on 2020-10-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models
import post.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=post.models.create_slug, editable=False, max_length=5, unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to=post.models.upload_location, validators=[post.validators.validate_file_extension])),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('dislikes', models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL, verbose_name='dislike')),
                ('favorites', models.ManyToManyField(related_name='favorited', to=settings.AUTH_USER_MODEL, verbose_name='favorites')),
                ('likes', models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='like')),
            ],
        ),
    ]
