# Generated by Django 3.1.1 on 2020-10-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201010_1451'),
        ('post', '0002_auto_20201010_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='category.category', verbose_name='category'),
        ),
    ]
